# Generated by Django 5.0 on 2023-12-21 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fueling Date')),
                ('gallons', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gas_type', models.CharField(choices=[('U', 'Unleaded'), ('P', 'Plus Unleaded'), ('R', 'Premium Unleaded')], default='U', max_length=1)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
